name: my_first_project
description: A new Flutter project.

environment:
  sdk: ">=3.7.0 <4.0.0"  # Add this SDK constraint

dependencies:
  flutter:
    sdk: flutter
  sms_advanced: ^1.1.0
  firebase_core: ^3.12.1
  google_fonts: ^6.2.1
  firebase_auth: ^5.5.1
  geolocator: ^13.0.3
  google_maps_flutter: ^2.12.0
  cloud_firestore: ^5.6.5
  fluttertoast: ^8.2.12
  twilio_flutter: ^0.9.0
  sensors_plus: ^6.1.1

  # Add other dependencies here
  # Example:
  # firebase_core: ^1.10.6
  # firebase_auth: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/Montserrat-Bold.ttf
          weight: 700

  assets:
    - assets/logo.png.jpg
    - assets/logo1.png.jpg
    - assets/logo3.jpg
    - assets/logo2.png
    - assets/fakecal.png.jpg
    - assets/sos.png.jpg
